[theme]
primaryColor = "#007bff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7fa"
textColor = "#000000"
font = "sans serif"

[server]
headless = true

# [client]
# initialSidebarState = "expanded"

# [general]
# pageTitle = "KOMI Scraper | KOMI Group"
